CREATE TABLE IF NOT EXISTS portfolio (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    cash_balance DECIMAL(12,2) NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS position (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    portfolio_id BIGINT NOT NULL,
    symbol VARCHAR(4) NOT NULL,
    quantity INT NOT NULL DEFAULT 0,
    cost_basis DECIMAL(12,2) NOT NULL DEFAULT 0,
    FOREIGN KEY (portfolio_id) REFERENCES portfolio(id)
);

CREATE TABLE IF NOT EXISTS stock_price (
    symbol VARCHAR(4) PRIMARY KEY,
    price DECIMAL(10,2) NOT NULL,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS intensity_level (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    level VARCHAR(32) NOT NULL DEFAULT 'PAPER_HANDS',
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS chaosevent_incident_log (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    headline VARCHAR(512) NOT NULL,
    target_symbol VARCHAR(4) NOT NULL,
    impact_percent DECIMAL(10,2) NOT NULL,
    explanation VARCHAR(2048),
    affected_symbols VARCHAR(2048),
    source_headline VARCHAR(512),
    event_type VARCHAR(32),
    event_severity VARCHAR(16),
    occurred_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS trade_history (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    portfolio_id BIGINT NOT NULL,
    action VARCHAR(4) NOT NULL,
    symbol VARCHAR(4) NOT NULL,
    quantity INT NOT NULL,
    price DECIMAL(10,2) NOT NULL,
    total_cost DECIMAL(12,2) NOT NULL,
    cash_balance_after DECIMAL(12,2) NOT NULL,
    executed_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (portfolio_id) REFERENCES portfolio(id)
);
