CREATE TABLE IF NOT EXISTS intensity_level (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    level VARCHAR(32) NOT NULL DEFAULT 'PAPER_HANDS',
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);
